name = "Enhanced 1920x1080 experience"
uid = "a97e6f92-ed8d-4017-ab9b-9e1b4db40333"
version = 0.1
date = 03-24-2015
copyright = "nah"
author = "partytime"
description = "A few tweaks to the ui for people who like to play the game in windowed mode, split screen over two 1920x1080 monitors. Starts the game in split screen, one click away from placing a land factory, with collapsed multifunction and tab controls. Moves the avatars control (idle units ui) to the left screen. Unlocks the ui so you can place your factory straight away."
exclusive = false
ui_only = true
conflicts = {}
requires = {} 
before = {}
after = {}
