name = "Selection Lock"
version = 3.0
copyright = "nah"
description = "Prevents selection of assisting units. You can still select one at a time. Can configure to limit by unit type. Special thanks to yorick + Sir Prize + Crotalus + Coding Squirrel and Morax"
author = "partytime"
url = ""
uid = "9C801555-8FAA-47EA-93A2-8AC9EE16B069"
exclusive = false
ui_only =true
conflicts = {}
