name = "UI Party"
version = 4
copyright = "nah"
description = "Various UI Enhancements. With contributions from many."
author = "partytime, with contributions (technical help / ideas / I stole their code) from Zock, Domino, Myxir, yorick, Sir Prize, Crotalus, Coding Squirrel, Morax"
url = ""
uid = "022E3DB4-9C00-4ED7-84D1-4866D316E694"
exclusive = false
ui_only =true
conflicts = {  }
