name = "LazyShare_for_FAF"
uid = "08e19d0f-0bc7-4c2f-89fc-be601373a7fa"
version = 3
copyright = "Copyright 2008, SvartfaR, adapted to UI of FA 1.5.3625 and GW Rank names by Koecher 2013"
description = "Quick share support for units and ressources via Keyboard. V2.0 by SvartfaR. Adapted to new Score UI (3625) and GW by Koecher, Beta3"
author = "SvartfaR, Koecher"
url = ""
icon = "/mods/lazyshare/lazy_share.dds"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
