name = "Idle Engineers"
uid = "b2cde810-15d0-4bfa-af66-ec2d6ecd561d"
version = 2
copyright = "camelCase"
description = "Highlight Idle Engineers on the main map"
author = "camelCase"
url = ""
icon = "/mods/idleEngineers/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = { }
before = {}
after = {}
