name = "UI-Plus"
version = 1
copyright = "nah"
description = "Various UI Enhancements. With contributions from many."
author = "partytime"
url = ""
uid = "24DD23CA-DDBA-41FB-840B-3ED1668FA5B3"
exclusive = false
ui_only =true
conflicts = {}
