name = "SelenDeselect"
version = 1.0
copyright = "yorick"
description = "Deselects idle Selens, which are on Hold-Fire , so you dont move the accidently. You still can select them one at a time"
author = "yorick"
url = ""
uid = "7ebfbd40-88df-4308-b1df-975a34fa77a8"
exclusive = false
ui_only =true
conflicts = {}
