name = "ZeP_MiniMapZoom"
uid = "5F593E02-FEF3-487C-916F-D6020903054B"
version = 2
copyright = ""
description = "Disabling minimap when zoomed out"
author = "Ze_PilOt"
url = ""
icon = "/mods/ZeP_MiniMapZoom/minimapmodicon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}